config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #to create a route, use any of the methods offered by rails 
  #that are named after all available HTTP methods (e.g. get, post, put, patch, delete)

  #The first argument is a URL path as a string.  
  #Then, provide the named argument "to" with string that 
  #gives the location of an action in a controller. 

  #EXAMPLE: 'to: "welcome#index"' directs the request
  #to the welcome_controller with the action "index"
  get("/", to: "welcome#index", as: :root)

  #routes will creates methods that are usable in your controllers
  #and views that wil return the url  or url path to a route.
  #this is tremendously useful when creating links.

  #The name of these will generate from the first argument.  
  #Otherwise it will use the named arg. 'as''s value.

  #The 'get' above will create: 
  # - root_path -> "/"
  # - root_url -> "http://localhost:3000/"
  
  
  get("/contact", to: "contact#index")
  #Methods provided: `contact_path` and `contact_url`
  post("/contact/submit", to: "contact#submit")

end



#TO VIEW ALL ROUTES AVAILABLE IN YOUR APPLICATION, 
#RUN 'RAILS ROUTES' IN THE  COMMAND TERMINAL.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end

    def submit
        #in rails, all of Expresses req.params, req.query, & req.body are combined into 'params'
        # render json: params

    #^^ use 'RENDER JSON: PARAMS as you 'res.send)req.body)' 
    #in express to show data in the browser as JSON. 
    #useful to learn for debuggings
      
    #To use variables in templates, create them as instance variables 
    # in your controller actions and methods.
    @message = "Thank you for contacting us!"
        render :index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    #a controller's public methods are called "actions".
    #Actions will handle requests from the user, render
    #a response, and reply with it.
    def index
        #use the 'render' method inside a controller action
        #to build the content of the response.
        #Using it with the "plain" named arg. will just render plain text.
        #render(plain: "Hello, Sexy")
        
        render :index

        #If you name your views after the controller's action,
        # you can omit the render.  Rails will  always look
        # for a file named after the action in asub-directory
        # of views/ named after the controller even if you 
        # do not call "render"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<p>Contact Us</p>

<% if @message %>
<p>
<%= @message %>
</p>
<% end %>

<%= form_tag(contact_submit_path) do %>
    <div>
        <%= label_tag(:full_name) %> <br/>
        <%= text_field_tag(:full_name) %>
    </div>

    <div>
        <%=  label_tag(:email) %> <br/>
        <%= email_field_tag(:email) %>
    </div>

    <div>
        <%= label_tag(:message) %> <br/>
        <%= text_area_tag(:message, nil, cols: 80, rows: 5) %>
    </div>
    <%= submit_tag("Contact Us!") %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🕶 AwesomeAnswers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <nav>
       <!-- <a href="<%= root_path %> ">Home</a>-->
        <%= link_to("Home", root_path) %>
        <%= link_to("Contact", contact_path)%>
  <%#
  In a layout file, the 'yield' is replaced with the contents of an erb
    template that we  render with the 'render' method.
    %>
    
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Awesome Answers!</h1>